# This file overrides the compose.yml file for running locally with dev services.

services:
    api:
        environment:
            DEV_MODE: true
            DEV_SERVICES: true
        env_file:
            - env/.env.api
        depends_on:
            kafka:
                condition: service_healthy
            redis:
                condition: service_healthy
            mongodb:
                condition: service_healthy

    agent:
        environment:
            DEV_MODE: true
            DEV_SERVICES: true
        env_file:
            - env/.env.agent
