# This file overrides the compose.yml file for development purposes.
# It removes the .env env_file from the api and agent services, and adds the DEV_SERVICES environment variable
# as now the services use local services.

services:
    api:
        environment:
            DEV_MODE: true
            DEV_SERVICES: true
        env_file:
            - env/.env.agent
        depends_on:
            kafka:
                condition: service_healthy
            redis:
                condition: service_healthy
            mongodb:
                condition: service_healthy

    agent:
        environment:
            DEV_MODE: true
            DEV_SERVICES: true
        env_file:
            - env/.env.agent
