services:
    api:
        profiles: ["dev", "prod"]
        build:
            context: .
            dockerfile: Dockerfile.api
        volumes:
            - .:/app
        ports:
            - "8080:8080"
        networks:
            - internal
            - external
        healthcheck:
            test: curl --fail http://localhost:8080/health || exit 1
            interval: 10s
            start_period: 30s
        restart: on-failure

    cli:
        profiles: ["dev", "prod"]
        build:
            context: .
            dockerfile: Dockerfile.cli
        volumes:
            - .:/app
        restart: on-failure

    agent:
        profiles: ["dev", "prod"]
        build:
            context: .
            dockerfile: Dockerfile.agenv
        depends_on:
            api:
                condition: service_healthy
        volumes:
            - .:/app
        networks:
            - internal
        restart: on-failure

volumes:
    mongo-data:
    mongo-config:

networks:
    internal:
        driver: bridge
    external:
        driver: bridge
