services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.api.dev
        volumes:
            - .:/app
        environment:
            KAFKA_GROUP_ID: api
            DEV_MODE: true
            DEV_SERVICES: false
        ports:
            - "8080:8080"
        networks:
            - internal
            - external
        healthcheck:
            test: curl --fail http://localhost:8080/health || exit 1
            interval: 10s
            start_period: 30s
        restart: on-failure

    cli:
        build:
            context: .
            dockerfile: Dockerfile.cli.dev
        volumes:
            - .:/app
        restart: on-failure

    agent:
        build:
            context: .
            dockerfile: Dockerfile.agent.dev
        depends_on:
            api:
                condition: service_healthy
        volumes:
            - .:/app
        environment:
            KAFKA_GROUP_ID: agent
            VELOCITY_URL: http://api:8080
            DEV_MODE: true
            DEV_SERVICES: false
        networks:
            - internal
        restart: on-failure

networks:
    internal:
        driver: bridge
    external:
        driver: bridge
