tests:
    - name: Unit tests
      language: golang
    - name: Integration Tests
      commands:
          - shell: make test
    - name: Testdata Golang
      directory: testdata/golang/std
      language: golang

images:
    - name: golang
      image: golang:latest

jobs:
    - name: Golang tests
      tests:
          - Unit tests
          - Integration Tests
      images:
          - golang
    - name: Testdata Golang
      tests:
          - Testdata Golang
      images:
          - golang

routines:
    - name: All tests
      jobs:
          - Golang tests
          - Testdata Golang
    - name: Self tests
      jobs:
          - Golang tests
