# This file overrides the compose.yml file for running locally with production services.

services:
    api:
        environment:
            DEV_SERVICES: false
        env_file:
            - env/.env.prod

    agent:
        environment:
            DEV_SERVICES: false
        env_file:
            - env/.env.prod
