services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.5.0
        profiles: ["dev"]
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - internal
        healthcheck:
            test: nc -z localhost 2181 || exit -1
            interval: 10s
            timeout: 5s
            retries: 3

    kafka:
        image: confluentinc/cp-kafka:7.5.0
        profiles: ["dev"]
        depends_on:
            zookeeper:
                condition: service_healthy
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
            KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
            KAFKA_SASL_JAAS_CONFIG: >
                org.apache.kafka.common.security.scram.ScramLoginModule required\
                username="admin"\
                password="password";
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        networks:
            - internal
        healthcheck:
            test: kafka-topics --bootstrap-server kafka:9092 --list
            interval: 30s
            timeout: 10s
            retries: 3
        restart: on-failure

    api:
        env_file:
            - env/.env.kafka

    agent:
        env_file:
            - env/.env.kafka
